apiVersion: v1
kind: Template
metadata:
  name: tomcat-demo-template
  annotations:
    description: "Description Tomcat demo template"
objects:
 - apiVersion: v1
   kind: Deployment
   apiVersion: extensions/v1beta1
   metadata:
     name: tomcat-demo
     creationTimestamp: 
     labels:
       run: tomcat-demo
   spec:
     selector:
       matchLabels:
         run: tomcat-demo
     template:
       metadata:
         creationTimestamp: 
         labels:
           run: tomcat-demo
       spec:
         containers:
         - name: tomcat-demo
           image: "${DOCKER_URL}"
           env:
           - name: KUBERNETES_NAMESPACE
             value: "${KUBERNETES_NAMESPACE}"
           ports:
           - containerPort: 8080
           readinessProbe:
             httpGet:
               path: /demo-1.0/health
               port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
           resources: {}
     strategy: {}
   status: {}
parameters:
  - name: DOCKER_URL
    displayName: Docker image URL
    description: The URL where you pushed the image
    required: true
  - name: KUBERNETES_NAMESPACE
    displayName: Name Space or Project
    description: The name space or the project you have created for app
    required: true
